controller_list:
  - name: fake_jenga_robot_controller
    joints:
      - turntable_joint
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
  - name: fake_jenga_gripper_controller
    joints:
      - gripper_joint